public enum EventType {
    WILD_FRUIT,
    WAGON_BROKEN,
    WAGON_FIRE,
    WAGON_ROBBED,
    OXEN_INJURED_OR_DEAD,
    PERSON_HAS_DISEASE,
    PERSON_HAS_BROKEN,
    PERSON_HAS_DIED,
    FIND_ABANDONED_WAGON,
    NOTHING_HAPPENS
}
